npm install @syncfusion/ej2-angular-buttons
npm install @syncfusion/ej2-angular-calendars
npm install @syncfusion/ej2-angular-inputs
npm install @syncfusion/ej2-angular-kanban
npm install @syncfusion/ej2-angular-schedule
npm install @syncfusion/ej2-angular-dropdowns
npm install @syncfusion/ej2-angular-charts
npm install @syncfusion/ej2-angular-lists
npm install @syncfusion/ej2-angular-navigations
npm install @syncfusion/ej2-angular-circulargauge
npm install @syncfusion/ej2-angular-grids
npm install @syncfusion/ej2-angular-popups
npm install @syncfusion/ej2-angular-maps
npm install @syncfusion/ej2-angular-splitbuttons
npm install @syncfusion/ej2-angular-documenteditor
npm install @syncfusion/ej2-compression
npm install @syncfusion/ej2-data
npm install @syncfusion/ej2-file-utils
